### PR TITLE
Made changes to winner messaging to show which player won

### PR DESCRIPTION
**Pull request by thephil16**
Also made change to server start to reduce CPU usage in countdown

### CODE REVIEW

**Comment by thephil16** [comment]
Should resolve #53

**Comment by thephil16** [comment]
Additional changes to resolve less than 2 joining server

**Comment by JohnZoldos** [comment]
I pulled master-pga and I'm still seeing the exact same issue as #53

**Comment by JohnZoldos** [comment]
Actually, it might be the case that it only happens now when a player wins after having placed a tiger at some point in the game. In this log Player 2 wins Game A by placing all totoro, 1 tiger, and all its villagers, but Player 1 is awarded the win.

https://pastebin.com/zd948E0J

**Comment by thephil16** [comment]
Updated to reflect correct winner in log. Seems to be scored correctly in tournament.

**Comment by JohnZoldos** [comment]
https://pastebin.com/Lq4aQmYR 
Still happening here. Player 1 forfeits but is listed as the winner.

**Comment by JohnZoldos** [comment]
Only seems to happen in situations where the winner placed a tiger or where the loser forfeited.

**Review by r3h4 — APPROVED** [review]
Looks good to me. Matt may have already fixed some of these but this should work

**Comment by JohnZoldos** [comment]
I just want to point out, in case nobody noticed, that this branch doesn't appear to have been merged with the master.

**Comment by MatthewBregg** [comment]
Problems!
Breaks everything!

**Pull request closed without merging**
